---
Data Creator : Badi James
Experiment Description : >
    Test experiment configuration 
    for Kaka
Experiment Code : 123456
Upload Date : 
    !!python/object/new:datetime.datetime
        - 2016
        - 01
        - 08
Experiment Date :
    !!python/object/new:datetime.datetime
        - 2016
        - 01
        - 07
...